fix: add error message

diff --git a/bin/vimenv b/bin/vimenv
--- a/bin/vimenv
+++ b/bin/vimenv
@@ -110,6 +110,7 @@ build_vim()
 	cd $TOPDIR/src/$TARGET/src
 	git checkout $VERSION 1>/dev/null 2>&1
 	if [ $? -ne 0 ]; then
+		echo "Error: git checkout $VERSION" 1>&2
 		return 1
 	fi
 
